US:
  name: "United States"
  states:
    AK: "Alaska"
    AL: "Alabama"
    AR: "Arkansas"
    AZ: "Arizona"
    CA: "California"
    CO: "Colorado"
    CT: "Connecticut"
    DC: "District of Columbia"
    DE: "Delaware"
    FL: "Florida"
    GA: "Georgia"
    HI: "Hawaii"
    IA: "Iowa"
    ID: "Idaho"
    IL: "Illinois"
    IN: "Indiana"
    KS: "Kansas"
    KY: "Kentucky"
    LA: "Louisiana"
    MA: "Massachusetts"
    MD: "Maryland"
    ME: "Maine"
    MI: "Michigan"
    MN: "Minnesota"
    MO: "Missouri"
    MS: "Mississippi"
    MT: "Montana"
    NC: "North Carolina"
    ND: "North Dakota"
    NE: "Nebraska"
    NH: "New Hampshire"
    NJ: "New Jersey"
    NM: "New Mexico"
    NV: "Nevada"
    NY: "New York"
    OH: "Ohio"
    OK: "Oklahoma"
    OR: "Oregon"
    PA: "Pennsylvania"
    RI: "Rhode Island"
    SC: "South Carolina"
    SD: "South Dakota"
    TN: "Tennessee"
    TX: "Texas"
    UT: "Utah"
    VA: "Virginia"
    VT: "Vermont"
    WA: "Washington"
    WI: "Wisconsin"
    WV: "West Virginia"
    WY: "Wyoming"
CA:
  name: "Canada"
  states:
    AB: "Alberta"
    BC: "British Columbia"
    MB: "Manitoba"
    NB: "New Brunswick"
    NL: "Newfoundland and Labrador"
    NS: "Nova Scotia"
    NT: "Northwest Territories"
    NU: "Nunavut"
    ON: "Ontario"
    PE: "Prince Edward Island"
    QC: "Quebec"
    SK: "Saskatchewan"
    YT: "Yukon"
MX:
  name: "Mexico"
  states:
    AGU: "Aguascalientes"
    BCN: "Baja California"
    BCS: "Baja California Sur"
    CAM: "Campeche"
    CHH: "Chihuahua"
    CHP: "Chiapas"
    CMX: "Mexico City"
    COA: "Coahuila"
    COL: "Colima"
    DUR: "Durango"
    GRO: "Guerrero"
    GUA: "Guanajuato"
    HID: "Hidalgo"
    JAL: "Jalisco"
    MEX: "México"
    MIC: "Michoacán"
    MOR: "Morelos"
    NAY: "Nayarit"
    NLE: "Nuevo León"
    OAX: "Oaxaca"
    PUE: "Puebla"
    QUE: "Querétaro"
    ROO: "Quintana Roo"
    SIN: "Sinaloa"
    SLP: "San Luis Potosí"
    SON: "Sonora"
    TAB: "Tabasco"
    TAM: "Tamaulipas"
    TLA: "Tlaxcala"
    VER: "Veracruz"
    YUC: "Yucatán"
    ZAC: "Zacatecas"